### ISSUE TITLE
Probably there is an indempotence issue.

### ISSUE THREAD

**Issue by eadgbe** [cloudpassage/cloudpassage-chef-cookbook#41]
When I try to rerun the cookbook, after a successful installation, I receive an error indicating that the service restart went bad. If I log into the host the service is stopped and it is not able to restart/start only after running  /opt/cloudpassage/bin/configure --agent-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx

This occurs in an AWS OpsWorks host. 

Chef log: 

[2016-06-20T22:20:42+00:00] INFO: Processing execute[cphalo-config] action run (/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb line 69)
[2016-06-20T22:20:42+00:00] INFO: Processing service[CloudPassage Halo Agent for Linux] action restart (/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb line 77)
# 
# Error executing action `restart` on resource 'service[CloudPassage Halo Agent for Linux]'
## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service cphalod restart ----
STDOUT: Stopping the CloudPassage Halo Agent...  [FAILED] 
Please run /opt/cloudpassage/bin/configure[FAILED]
STDERR: 
---- End output of /sbin/service cphalod restart ----
Ran /sbin/service cphalod restart returned 1
## Cookbook Trace:

/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in`compile_and_converge_action'
/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
## Resource Declaration:
# In /var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb

77:     service 'CloudPassage Halo Agent for Linux' do
78:       service_name 'cphalod'
79:       # Force systemd for RHEL 7+.
80:       if (%w(redhat centos).include? node['platform']) && node['platform_version'].to_f >= 7
81:         provider Chef::Provider::Service::Systemd
82:       end
83:       supports [:start, :stop, :restart]
## Compiled Resource:
# Declared in /var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb:77:in `block in class_from_file'

service("CloudPassage Halo Agent for Linux") do
action [:restart]
supports {:restart=>true, :reload=>nil, :status=>nil, :start=>true, :stop=>true}
retries 0
retry_delay 2
default_guard_interpreter :default
service_name "cphalod"
pattern "CloudPassage Halo Agent for Linux"
declared_type :service
cookbook_name "cloudpassage"
end
## Platform:

x86_64-linux

[2016-06-20T22:20:43+00:00] INFO: Running queued delayed notifications before re-raising exception
# 
# Error executing action `install` on resource 'cloudpassage_agent[halo]'
## Mixlib::ShellOut::ShellCommandFailed

service[CloudPassage Halo Agent for Linux](/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service cphalod restart ----
STDOUT: Stopping the CloudPassage Halo Agent...  [FAILED] 
Please run /opt/cloudpassage/bin/configure[FAILED]
STDERR: 
---- End output of /sbin/service cphalod restart ----
Ran /sbin/service cphalod restart returned 1
## Cookbook Trace:

/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in`compile_and_converge_action'
/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
## Resource Declaration:
# In /var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/recipes/default.rb

27: cloudpassage_agent 'halo' do
28:   agent_key final_config['agent_key']
29:   linux_agent_version final_config['linux_agent_version']
30:   grid_url final_config['grid_url']
31:   proxy_host final_config['proxy_host']
32:   proxy_port final_config['proxy_port']
33:   proxy_user final_config['proxy_user']
34:   proxy_password final_config['proxy_password']
35:   read_only final_config['read_only']
36:   server_tag final_config['server_tag']
37:   server_label final_config['server_label']
38:   dns final_config['dns']
39:   windows_installer_protocol final_config['windows_installer_protocol']
40:   windows_installer_port final_config['windows_installer_port']
41:   windows_installer_host final_config['windows_installer_host']
42:   windows_installer_path final_config['windows_installer_path']
43:   windows_installer_file_name final_config['windows_installer_file_name']
44:   apt_repo_url final_config['apt_repo_url']
45:   apt_repo_distribution final_config['apt_repo_distribution']
46:   apt_repo_components final_config['apt_repo_components']
47:   yum_repo_url final_config['yum_repo_url']
48:   apt_key_url final_config['apt_key_url']
49:   yum_key_url final_config['yum_key_url']
50:   action :install
51: end
## Compiled Resource:
# Declared in /var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/recipes/default.rb:27:in `from_file'

cloudpassage_agent("halo") do
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :cloudpassage_agent
cookbook_name "cloudpassage"
recipe_name "default"
agent_key "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
linux_agent_version "3.7.6"
grid_url "https://grid.cloudpassage.com/grid"
dns true
windows_installer_protocol "https"
windows_installer_port "443"
windows_installer_host "packages.cloudpassage.com"
windows_installer_path "/windows/"
windows_installer_file_name "cphalo-3.7.6-win64.exe"
apt_repo_url "http://packages.cloudpassage.com/debian"
apt_repo_distribution "debian"
apt_repo_components ["main"]
yum_repo_url "http://packages.cloudpassage.com/redhat/$basearch"
apt_key_url "http://packages.cloudpassage.com/cloudpassage.packages.key"
yum_key_url "http://packages.cloudpassage.com/cloudpassage.packages.key"
end
## Platform:

x86_64-linux

[2016-06-20T22:20:43+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-06-20T22:20:43+00:00] INFO: template[/etc/ntp.conf] sending restart action to service[ntpd](delayed)
[2016-06-20T22:20:43+00:00] INFO: Processing service[ntpd] action restart (ntp::default line 112)
[2016-06-20T22:20:43+00:00] INFO: service[ntpd] restarted
[2016-06-20T22:20:43+00:00] ERROR: Running exception handlers
[2016-06-20T22:20:43+00:00] ERROR: Exception handlers complete
[2016-06-20T22:20:43+00:00] FATAL: Stacktrace dumped to /var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/chef-stacktrace.out
[2016-06-20T22:20:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-06-20T22:20:43+00:00] ERROR: cloudpassage_agent[halo](cloudpassage::default line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: service[CloudPassage Halo Agent for Linux](/var/chef/runs/ce14bda5-9146-4530-ac8d-b86b6b0313a3/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service cphalod restart ----
STDOUT: Stopping the CloudPassage Halo Agent...  [FAILED] 
Please run /opt/cloudpassage/bin/configure[FAILED]
STDERR: 
---- End output of /sbin/service cphalod restart ----
Ran /sbin/service cphalod restart returned 1
[2016-06-20T22:20:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by eadgbe** [comment]
I just saw one comment in your code:

# We don't run the configurator if the store.db file already exists

https://github.com/cloudpassage/cloudpassage-chef-cookbook/blob/master/resources/agent.rb#L74

Please ignore this "issue".

I just need to delete the file in my code:

file '/opt/cloudpassage/data/store.db' do
  action :delete
  only_if { File.exist? '/opt/cloudpassage/data/store.db' }
end

Thanks.
